name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  source:
    name: Source Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # - name: Run tests
    #   run: |
    #     python manage.py test

    - name: Generate deployment package
      run: |
        zip -r deploy.zip . -x "*.git*" -x "node_modules/*" -x "venv/*"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: deploy.zip


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Download Artifact
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: deployment-package

  #   - name: Deploy to Elastic Beanstalk
  #     uses: einaregilsson/beanstalk-deploy@v18
  #     with:
  #       aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  #       aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
  #       region: 'us-east-1'
  #       application_name: 'HomeHunt'
  #       environment_name: 'new-homehunt-env'
  #       version_label: ${{ github.sha }}
  #       deployment_package: deploy.zip