name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  source:
    name: Source Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     # Assuming you are using Django's default test runner
    #     python manage.py test

    # - name: Deploy to Elastic Beanstalk
    #   uses: einaregilsson/beanstalk-deploy@v18
    #   with:
    #     aws_access_key: ${{ secrets.aws_access_key }}
    #     aws_secret_key: ${{ secrets.aws_secret_key }}
    #     region: 'us-east-1'
    #     application_name: 'HomeHunt'
    #     environment_name: 'new-homehunt-env'
    #     version_label: ${{ github.sha }}
    #     deployment_package: path/to/your/deployment.zip